### ISSUE TITLE
Apache comparison fail?

### ISSUE THREAD

**Issue by tieguy** [spdx/spdx-license-diff#11]
This plugin has been *amazing* for me, so thanks so much for writing it!

Ran into my first weird problem with it: when I select the main body text at https://www.apache.org/licenses/LICENSE-2.0 it returns... well, not Apache :) Screenshot attached.

<img width="551" alt="Screen Shot 2019-05-21 at 5 03 16 PM" src="https://user-images.githubusercontent.com/660541/58138297-5d562080-7bea-11e9-8ec2-9245346cb1f0.png">

**Comment by alandtse** [comment]
Thanks for catching that. What is happening is the official [Apache text](https://www.apache.org/licenses/LICENSE-2.0.txt) also includes the `How to Apply` section so by not including that section, Apache-2.0 is filtered early.  We currently have a default setting to ignore any text that is more than 1000 chars different in length.  The missing section is about ~1300 chars.  To solve this, you can change the Advanced Option for `Maximum length difference` to `1400`.  This will slow down the comparison overall, but will be more accurate.

**Comment by alandtse** [comment]
This is probably a common issue so perhaps I'll bump up the default setting unless someone chimes in they think the compare is too slow.
