### ISSUE TITLE
Exceptions.json has changed format of detailsUrl

### ISSUE THREAD

**Issue by alandtse** [spdx/spdx-license-diff#118]
Unlike [licenses.json](https://spdx.org/licenses/licenses.json), [exceptions.json](https://spdx.org/licenses/exceptions.json) appears to give a relative url for [detailsUrl](https://github.com/spdx/license-list-data/blob/main/accessingLicenses.md?plain=1#L109) instead of the full url.

This appears to be a recent change but I'm not sure when. @goneall , I haven't been active recently but noticed it recently broke the license-diff tool. I can do a fix, but wanted to make sure it was intentional.

**Comment by goneall** [comment]
Interesting - I'm not quite sure what change would have caused this.

I think we should fix the publisher to use the full URL.

@alandtse - do you want me to move this over to the publisher?  It would probably take a couple months to cycle through the release processes for both the tools and the license list.  We can also open a new issue if you want to update this utility to handle either format.

**Comment by alandtse** [comment]
Oh wait, it appears that it's also not a json now. Compare `reference` with `detailsUrl` across both licenses and exceptions.

**Comment by alandtse** [comment]
Can you create a new ticket to address? I'll do a fix in the tool here and close this one.

**Comment by goneall** [comment]
@alandtse created https://github.com/spdx/LicenseListPublisher/issues/169 to track updating the License List Publisher.  Feel free to add any details to the new issue.

**Comment by alandtse** [comment]
This should be resolved within the tool.
