### ISSUE TITLE
on libevent.org/LICENSE.txt first or last sections sticks at 1/100 Processing...

### ISSUE THREAD

**Issue by BrianInglis** [spdx/spdx-license-diff#119]
Under *Windows* 22H2 10.0.19045.3448 running *ungoogled* `Chromium` 116.0.5845.180 with URI [libevent licence](https://libevent.org/LICENSE.txt) selecting either the first or last sections of the text from the second *Copyright* line (in case `sld` does not handle more than one instance) a small text character box overlays the top left of the window and shows no progress from
```
1/100
Processing...
```

**Comment by alandtse** [comment]
Does it process any files? Typically if it's 1/100 there's more fundamental issues such as not being able to spawn background workers.

**Comment by BrianInglis** [comment]
Not that I've found even on SPDX License List - same status message! 
Are there privacy and security settings which need to be enabled to allow those to run? Images and JS are set to Allow, Sound is Mute, rest are set to Ask or Block! 
Are there certain startup options or chrome://flags/ required? 
Other extensions such as EpubReader, FoxishLiveRSS, MarkdownViewer, SetCharacterEncoding, and various Privacy and Security blockers work okay.

**Comment by BrianInglis** [comment]
Not so far, even SPDX 0BSD shows the same status message. 
*Privacy and Security* settings are mostly `Ask` or `Block`, *Sound* is `Mute`, *Images* and *JS* are `Allow`. 
Other similar extensions such as *EpubReader*, *FoxishLiveRSS*, *MarkdownViewer*, *SetCharacterEncoding*, plus various blockers work fine, and file:// URIs are enabled for each, as I use many locally. 
Are any specific *startup options* or `chrome://flags/` required to be enabled or disabled? 
I have increased `flag` *max connections per host* from 6 to 15 and reloaded.

**Comment by BrianInglis** [comment]
Extension Permissions are:
```
SPDX License Diff (ID: kfoadicmilbgnicoldjmccpaicejacdh)
Usage			No usage data
Permissions
Location		Block (default)
Camera			Block (default)
Microphone		Block (default)
Motion sensors		Block (default)
Notifications		Block (default)
JavaScript		Allowlisted internally	Allow
Images			Allowlisted internally	Allow
Pop-ups and redirects	Allowlisted internally	Allow
Intrusive ads		Block if site shows intrusive or misleading ads	Block (default)
Background sync		Block (default)
Sound			Mute (default)
Automatic downloads	Allowlisted internally	Allow
MIDI devices		Block (default)
USB devices		Block (default)
Serial ports		Block (default)
File editing		Block (default)
HID devices		Block (default)
Protected content IDs	Block (default)
Clipboard		Block (default)
Payment handlers	Block (default)
Insecure content	Block (default)
Third-party sign-in	Allow (default)
Augmented reality	Block (default)
Virtual reality		Block (default)
Your device use		Ask (default)
Window management	Ask (default)
Fonts			Ask (default)
JavaScript JIT		Block (default)
Webgl			Block (default)
WebRTC			Block (default)
```

**Comment by alandtse** [comment]
None of those permissions should impact it.

Try going into extension options and `update list`. If nothing changes, you can try `clear storage` and then `update list`. 
<img width="677" alt="image" src="https://github.com/spdx/spdx-license-diff/assets/7086117/2e06b908-8dff-4f93-889b-68ed765f6746">

There are also debug logs on the Background Page under the Console tab. You can also get logs when you try to run the scan on the page you're using `Developer Tools` -> `Console`.

You should see an Contenscript injected message. 
<img width="634" alt="image" src="https://github.com/spdx/spdx-license-diff/assets/7086117/a9ca6947-eef3-40d1-a632-08eedc928106">

**Comment by BrianInglis** [comment]
Thanks Alan, `Clear Storage` and `Update List` did the trick. 
Quit and restarted `Chromium`. 
Successfully tested on *0BSD* and *libevent* chunks!
