### ISSUE TITLE
Add a context menu entry

### ISSUE THREAD

**Issue by omasanori** [spdx/spdx-license-diff#71]
In addition to the toolbar button, it would be great if clicking the right button on a selected text can start the license search.

**Comment by alandtse** [comment]
Thanks for the suggestion. I'll take a look at whether we can add the feature.

**Comment by alandtse** [comment]
Please update the extension to 0.7.0 to use the new feature. I just confirmed it's published for Chrome already.

**Comment by omasanori** [comment]
@alandtse Thank you for your prompt response and even implementation!
