### ISSUE TITLE
Diff display problem when text is an input field for Black Duck

### ISSUE THREAD

**Issue by stephenkilbaneadi** [spdx/spdx-license-diff#79]
This browser extension is fantastic, and I'm using it a lot - thank you!

One context I'm using it in is to check the license texts in Black Duck. Black Duck displays each license on a form where attributes can be edited - including the license text itself. This means that the selected text is in a multi-line text input field. The search works okay, but when the diff is displayed, matching text is displayed as plain black-on-black (or something similar - nothing's readable, anyway). Where there are differences, they appear as normal, amid the sea of black. If I compare the same text displayed normally on a page - e.g. spdx.org - the diff shows up perfectly. I see the same problem for both Chrome and Firefox.

**Comment by alandtse** [comment]
Thanks. Can you post a screenshot? We have a default color scheme which may be breaking in Blackduck. I only have access to Protex so I may not be able to test it myself.

**Comment by stephenkilbaneadi** [comment]
<img width="651" alt="spdx-diff-bug" src="https://user-images.githubusercontent.com/52311510/109295948-81b34800-7827-11eb-8acb-d27da6c1141b.png">

As seen when comparing the MIT text.

**Comment by alandtse** [comment]
Thanks. I just confirmed this isn't something I can see in Protex as it was changed in Black Duck. Can you provide the html for the form? You can save the page in chrome as HTML only. I don't know what BlackDuck is embedding in the page so you may want to scrub the html before you provide it.

**Comment by stephenkilbaneadi** [comment]
Any chance I could mail it to you directly, rather than attaching it here. Just in case I'm missing something in the HTML that should be scrubbed?

**Comment by alandtse** [comment]
Yes. Same name on gmail.

**Comment by alandtse** [comment]
Thinking about this more, I'm thinking the solution may be to allow the results to go to a new tab. Any thoughts on that?

**Comment by stephenkilbaneadi** [comment]
That would work for me.

**Comment by alandtse** [comment]
As a note, the feature is in the top right of the diff window now. Let me know if it doesn't work.

**Comment by stephenkilbaneadi** [comment]
Works well on Chrome – yay!

I see problems on Firefox, though (86.0), using Black Duck and spdx.org/licenses as test sites.

  *   The placement of the diff window seems to be arbitrary on the tab, and sometimes isn't visible at all. (I see this on Black Duck, not on spdx.org);
  *   The new diff tab opens, but doesn't display anything. If I leave the new tab open, click on the expand in the diff window to open a second diff tab, the second diff tab is empty, but now the first diff tab has the right contents. (I see this on both Black Duck and spdx.org).

The Firefox problems don't happen every time, but pretty frequently.

steve
